name: formio_flutter
description: A dynamic form rendering and submission package for Flutter using Form.io schemas.
version: 0.1.0
homepage: https://spinex.io
repository: https://github.com/mskayali/formio_flutter
issue_tracker: https://github.com/spinex-io/formio_flutter/issues


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  dio: ^5.0.0
  provider: ^6.0.0
  file_picker: ^6.1.1
  flutter_html: ^3.0.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
