name: formio
description: A dynamic form rendering and submission package for Flutter using Form.io schemas.
version: 0.1.1
homepage: https://spinex.io
repository: https://github.com/mskayali/formio_flutter
issue_tracker: https://github.com/mskayali/formio_flutter/issues


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  dio: ^5.0.0
  provider: ^6.0.0
  file_picker: ^10.3.3
  flutter_html: ^3.0.0
  intl: ^0.20.2
  signature: ^6.3.0
  omni_datetime_picker: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
