import 'package:flutter/material.dart';
import 'package:formio/formio.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'FormIO Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF6366F1),
          brightness: Brightness.light,
        ),
        useMaterial3: true,
        cardTheme: const CardThemeData(
          elevation: 2,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.all(Radius.circular(12)),
          ),
        ),
      ),
      debugShowCheckedModeBanner: false,
      home: const MyHomePage(title: 'Modern FormIO Demo'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late FormModel form;
  int index = 0;

  @override
  void initState() {
    super.initState();
    form = FormModel.fromJson(jsonData);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: SingleChildScrollView(
        child: Container(
          padding: EdgeInsets.all(20),
          child: FormRenderer(
            form: form,
            onChanged: (value) {
              setState(() {});
            },
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {},
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

Map<String, dynamic> jsonData = {
  '_id': '64a7b1f4e4b0c9001cfa5f3d',
  'path': 'registration',
  'title': 'Modern Registration Form',
  'name': 'registration',
  "components": [
    {
      "label": "Datos",
      "columns": [
        {
          "components": [
            {
              "label": "Client",
              "labelPosition": "top",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "prefix": "",
              "suffix": "",
              "widget": {"type": "input"},
              "inputMask": "",
              "displayMask": "",
              "applyMaskOn": "change",
              "allowMultipleMasks": false,
              "customClass": "",
              "tabindex": "",
              "autocomplete": "",
              "hidden": false,
              "hideLabel": false,
              "showWordCount": false,
              "showCharCount": false,
              "mask": false,
              "autofocus": false,
              "spellcheck": true,
              "disabled": false,
              "tableView": true,
              "modalEdit": false,
              "multiple": false,
              "inputFormat": "plain",
              "case": "",
              "truncateMultipleSpaces": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": false,
                "pattern": "",
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "minLength": "",
                "maxLength": "",
                "strictDateValidation": false,
                "multiple": false,
                "unique": false,
              },
              "validateWhenHidden": false,
              "errorLabel": "",
              "errors": "",
              "key": "cliente",
              "tags": [],
              "properties": {},
              "conditional": {"show": null, "when": null, "eq": "", "json": ""},
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "type": "textfield",
              "dataGridLabel": false,
              "input": true,
              "protected": false,
              "unique": false,
              "persistent": true,
              "refreshOn": "",
              "dbIndex": false,
              "calculateServer": false,
              "overlay": {
                "style": "",
                "left": "",
                "top": "",
                "width": "",
                "height": "",
              },
              "encrypted": false,
              "addons": [],
              "inputType": "text",
              "id": "evb3ks",
              "defaultValue": "",
            },
            {
              "label": "Venta Concretada?",
              "labelPosition": "left-left",
              "optionsLabelPosition": "right",
              "description": "",
              "tooltip": "",
              "customClass": "",
              "tabindex": "0",
              "inline": false,
              "hidden": false,
              "hideLabel": false,
              "autofocus": false,
              "disabled": false,
              "tableView": true,
              "modalEdit": false,
              "dataSrc": "values",
              "values": [
                {"label": "Si", "value": "si", "shortcut": "S"},
                {"label": "No", "value": "no", "shortcut": "N"},
                {"label": "Postergada", "value": "postergada", "shortcut": "P"},
              ],
              "dataType": "string",
              "valueProperty": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "allowCalculateOverride": false,
              "validate": {
                "required": false,
                "onlyAvailableItems": false,
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "strictDateValidation": false,
                "multiple": false,
                "unique": false,
              },
              "validateWhenHidden": false,
              "errorLabel": "",
              "errors": "",
              "key": "ventaConcretada",
              "tags": [],
              "properties": {},
              "conditional": {"show": null, "when": null, "eq": "", "json": ""},
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": "",
              },
              "type": "radio",
              "dataGridLabel": false,
              "data": {"url": ""},
              "template": "<span>{{ item.label }}</span>",
              "ignoreCache": false,
              "redrawOn": "",
              "input": true,
              "placeholder": "",
              "prefix": "",
              "suffix": "",
              "multiple": false,
              "protected": false,
              "unique": false,
              "persistent": true,
              "refreshOn": "",
              "dbIndex": false,
              "calculateServer": false,
              "widget": null,
              "validateOn": "change",
              "encrypted": false,
              "showCharCount": false,
              "showWordCount": false,
              "allowMultipleMasks": false,
              "addons": [],
              "authenticate": false,
              "inputType": "radio",
              "fieldSet": false,
              "id": "e5uwhu5",
              "defaultValue": "",
            },
            {
              "label": "Day",
              "hideInputLabels": false,
              "inputsLabelPosition": "top",
              "description": "",
              "useLocaleSettings": false,
              "tooltip": "",
              "customClass": "",
              "tabindex": "",
              "hidden": true,
              "hideLabel": false,
              "autofocus": false,
              "disabled": false,
              "tableView": false,
              "modalEdit": false,
              "fields": {
                "day": {
                  "type": "number",
                  "placeholder": "",
                  "hide": false,
                  "required": true,
                },
                "month": {
                  "type": "select",
                  "placeholder": "",
                  "hide": false,
                  "required": true,
                },
                "year": {
                  "type": "number",
                  "placeholder": "",
                  "hide": false,
                  "required": true,
                },
              },
              "dayFirst": false,
              "redrawOn": "ventaConcretada",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "allowCalculateOverride": false,
              "validateOn": "change",
              "maxDate": "",
              "minDate": "",
              "validateWhenHidden": false,
              "errorLabel": "",
              "validate": {
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "required": false,
                "strictDateValidation": false,
                "multiple": false,
                "unique": false,
              },
              "errors": "",
              "key": "day",
              "tags": [],
              "properties": {},
              "conditional": {"show": null, "when": null, "eq": "", "json": ""},
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "type": "day",
              "dataGridLabel": false,
              "input": true,
              "placeholder": "",
              "prefix": "",
              "suffix": "",
              "multiple": false,
              "protected": false,
              "unique": false,
              "persistent": true,
              "refreshOn": "",
              "labelPosition": "top",
              "dbIndex": false,
              "calculateServer": false,
              "widget": null,
              "overlay": {
                "style": "",
                "left": "",
                "top": "",
                "width": "",
                "height": "",
              },
              "encrypted": false,
              "showCharCount": false,
              "showWordCount": false,
              "allowMultipleMasks": false,
              "addons": [],
              "id": "e9l1yr",
              "defaultValue": "11/01/2025",
            },
            {
              "label": "Text Field",
              "labelPosition": "top",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "prefix": "",
              "suffix": "",
              "widget": {"type": "input"},
              "inputMask": "",
              "displayMask": "",
              "applyMaskOn": "change",
              "allowMultipleMasks": false,
              "customClass": "",
              "tabindex": "",
              "autocomplete": "",
              "hidden": false,
              "hideLabel": false,
              "showWordCount": false,
              "showCharCount": false,
              "mask": false,
              "autofocus": false,
              "spellcheck": true,
              "disabled": false,
              "tableView": true,
              "modalEdit": false,
              "multiple": false,
              "inputFormat": "plain",
              "case": "",
              "truncateMultipleSpaces": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": false,
                "pattern": "",
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "minLength": "",
                "maxLength": "",
                "strictDateValidation": false,
                "multiple": false,
                "unique": false,
              },
              "validateWhenHidden": false,
              "errorLabel": "",
              "errors": "",
              "key": "textField",
              "tags": [],
              "properties": {},
              "conditional": {"show": null, "when": null, "eq": "", "json": ""},
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "type": "textfield",
              "dataGridLabel": false,
              "input": true,
              "protected": false,
              "unique": false,
              "persistent": true,
              "refreshOn": "",
              "dbIndex": false,
              "calculateServer": false,
              "overlay": {
                "style": "",
                "left": "",
                "top": "",
                "width": "",
                "height": "",
              },
              "encrypted": false,
              "addons": [],
              "inputType": "text",
              "id": "ejf5awk",
              "defaultValue": null,
            },
            {
              "label": "Upload",
              "labelPosition": "top",
              "description": "",
              "tooltip": "",
              "customClass": "",
              "tabindex": "",
              "hidden": false,
              "hideLabel": false,
              "autofocus": false,
              "disabled": false,
              "tableView": false,
              "modalEdit": false,
              "storage": "url",
              "url": "",
              "fileTypes": [
                {"label": "", "value": ""},
              ],
              "options": "",
              "fileKey": "",
              "dir": "",
              "fileNameTemplate": "",
              "image": false,
              "privateDownload": false,
              "webcam": false,
              "uploadOnly": false,
              "filePattern": "*",
              "fileMinSize": "0KB",
              "fileMaxSize": "1GB",
              "multiple": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "allowCalculateOverride": false,
              "validate": {
                "required": false,
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "strictDateValidation": false,
                "multiple": false,
                "unique": false,
              },
              "validateWhenHidden": false,
              "errorLabel": "",
              "errors": "",
              "key": "file",
              "tags": [],
              "properties": {},
              "conditional": {"show": null, "when": null, "eq": "", "json": ""},
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "type": "file",
              "dataGridLabel": false,
              "imageSize": "200",
              "input": true,
              "placeholder": "",
              "prefix": "",
              "suffix": "",
              "defaultValue": null,
              "protected": false,
              "unique": false,
              "persistent": true,
              "refreshOn": "",
              "dbIndex": false,
              "calculateServer": false,
              "widget": null,
              "validateOn": "change",
              "overlay": {
                "style": "",
                "left": "",
                "top": "",
                "width": "",
                "height": "",
              },
              "encrypted": false,
              "showCharCount": false,
              "showWordCount": false,
              "allowMultipleMasks": false,
              "addons": [],
              "id": "ebkncis",
            },
            {
              "label": "Survey",
              "labelPosition": "top",
              "description": "",
              "tooltip": "",
              "customClass": "",
              "tabindex": "",
              "hidden": false,
              "hideLabel": false,
              "autofocus": false,
              "disabled": false,
              "tableView": false,
              "modalEdit": false,
              "questions": [
                {"label": "", "value": "", "tooltip": ""},
              ],
              "values": [
                {"label": "", "value": "", "tooltip": ""},
              ],
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "allowCalculateOverride": false,
              "validate": {
                "required": false,
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "strictDateValidation": false,
                "multiple": false,
                "unique": false,
              },
              "validateWhenHidden": false,
              "errorLabel": "",
              "errors": "",
              "key": "survey",
              "tags": [],
              "properties": {},
              "conditional": {"show": null, "when": null, "eq": "", "json": ""},
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "type": "survey",
              "dataGridLabel": false,
              "input": true,
              "placeholder": "",
              "prefix": "",
              "suffix": "",
              "multiple": false,
              "protected": false,
              "unique": false,
              "persistent": true,
              "refreshOn": "",
              "dbIndex": false,
              "calculateServer": false,
              "widget": null,
              "validateOn": "change",
              "overlay": {
                "style": "",
                "left": "",
                "top": "",
                "width": "",
                "height": "",
              },
              "encrypted": false,
              "showCharCount": false,
              "showWordCount": false,
              "allowMultipleMasks": false,
              "addons": [],
              "id": "e8tv2nf",
              "defaultValue": {},
            },
          ],
          "width": 6,
          "offset": 0,
          "push": 0,
          "pull": 0,
          "size": "md",
          "currentWidth": 6,
        },
        {
          "components": [
            {
              "label": "Signature",
              "footer": "Sign above",
              "labelPosition": "top",
              "width": "100%",
              "height": "150px",
              "backgroundColor": "rgb(245,245,235)",
              "penColor": "black",
              "description": "",
              "tooltip": "",
              "customClass": "",
              "tabindex": "",
              "hidden": false,
              "hideLabel": false,
              "disabled": false,
              "tableView": false,
              "modalEdit": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "allowCalculateOverride": false,
              "validate": {
                "required": false,
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "strictDateValidation": false,
                "multiple": false,
                "unique": false,
              },
              "validateWhenHidden": false,
              "errorLabel": "",
              "errors": "",
              "key": "signature",
              "tags": [],
              "properties": {},
              "conditional": {"show": null, "when": null, "eq": "", "json": ""},
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "type": "signature",
              "keepOverlayRatio": true,
              "dataGridLabel": false,
              "input": true,
              "placeholder": "",
              "prefix": "",
              "suffix": "",
              "multiple": false,
              "defaultValue": null,
              "protected": false,
              "unique": false,
              "persistent": true,
              "refreshOn": "",
              "autofocus": false,
              "dbIndex": false,
              "calculateServer": false,
              "widget": {"type": "input"},
              "validateOn": "change",
              "overlay": {
                "style": "",
                "left": "",
                "top": "",
                "width": "",
                "height": "",
              },
              "encrypted": false,
              "showCharCount": false,
              "showWordCount": false,
              "allowMultipleMasks": false,
              "addons": [],
              "minWidth": "0.5",
              "maxWidth": "2.5",
              "id": "e95ve0m",
            },
            {
              "label": "Checkbox",
              "description": "",
              "tooltip": "",
              "shortcut": "",
              "inputType": "checkbox",
              "customClass": "",
              "tabindex": "",
              "hidden": false,
              "hideLabel": false,
              "autofocus": false,
              "disabled": false,
              "tableView": false,
              "modalEdit": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "allowCalculateOverride": false,
              "validate": {
                "required": false,
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "strictDateValidation": false,
                "multiple": false,
                "unique": false,
              },
              "validateWhenHidden": false,
              "errorLabel": "",
              "errors": "",
              "key": "checkbox",
              "tags": [],
              "properties": {},
              "conditional": {"show": null, "when": null, "eq": "", "json": ""},
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "type": "checkbox",
              "name": "",
              "value": "",
              "dataGridLabel": true,
              "input": true,
              "placeholder": "",
              "prefix": "",
              "suffix": "",
              "multiple": false,
              "protected": false,
              "unique": false,
              "persistent": true,
              "refreshOn": "",
              "labelPosition": "right",
              "dbIndex": false,
              "calculateServer": false,
              "widget": null,
              "validateOn": "change",
              "overlay": {
                "style": "",
                "left": "",
                "top": "",
                "width": "",
                "height": "",
              },
              "encrypted": false,
              "showCharCount": false,
              "showWordCount": false,
              "allowMultipleMasks": false,
              "addons": [],
              "id": "emuws9d",
              "defaultValue": null,
            },
            {
              "label": "Select Boxes",
              "labelPosition": "top",
              "optionsLabelPosition": "right",
              "description": "",
              "tooltip": "",
              "customClass": "",
              "tabindex": "",
              "inline": false,
              "hidden": false,
              "hideLabel": false,
              "autofocus": false,
              "disabled": false,
              "tableView": false,
              "modalEdit": false,
              "dataSrc": "values",
              "values": [
                {"label": "value", "value": "value", "shortcut": "B"},
                {"label": "valye", "value": "valye", "shortcut": "A"},
              ],
              "valueProperty": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "allowCalculateOverride": false,
              "validate": {
                "required": false,
                "onlyAvailableItems": false,
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "strictDateValidation": false,
                "multiple": false,
                "unique": false,
              },
              "validateWhenHidden": false,
              "errorLabel": "",
              "minSelectedCountMessage": "",
              "maxSelectedCountMessage": "",
              "errors": "",
              "key": "selectBoxes",
              "tags": [],
              "properties": {},
              "conditional": {"show": null, "when": null, "eq": "", "json": ""},
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "type": "selectboxes",
              "dataGridLabel": false,
              "data": {"url": ""},
              "redrawOn": "",
              "input": true,
              "inputType": "checkbox",
              "placeholder": "",
              "prefix": "",
              "suffix": "",
              "multiple": false,
              "protected": false,
              "unique": false,
              "persistent": true,
              "refreshOn": "",
              "dbIndex": false,
              "calculateServer": false,
              "widget": null,
              "validateOn": "change",
              "overlay": {
                "style": "",
                "left": "",
                "top": "",
                "width": "",
                "height": "",
              },
              "encrypted": false,
              "showCharCount": false,
              "showWordCount": false,
              "allowMultipleMasks": false,
              "addons": [],
              "authenticate": false,
              "fieldSet": false,
              "id": "ejig8z4",
              "defaultValue": {},
              "ignoreCache": false,
              "template": "<span>{{ item.label }}</span>",
            },
            {
              "label": "Email",
              "labelPosition": "top",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "prefix": "",
              "suffix": "",
              "widget": {"type": "input"},
              "displayMask": "",
              "applyMaskOn": "change",
              "customClass": "",
              "tabindex": "",
              "autocomplete": "",
              "hidden": false,
              "hideLabel": false,
              "mask": false,
              "autofocus": false,
              "spellcheck": true,
              "disabled": false,
              "tableView": true,
              "modalEdit": false,
              "multiple": false,
              "inputFormat": "plain",
              "case": "",
              "truncateMultipleSpaces": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": false,
                "pattern": "",
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "minLength": "",
                "maxLength": "",
                "strictDateValidation": false,
                "multiple": false,
                "unique": false,
              },
              "unique": false,
              "validateWhenHidden": false,
              "errorLabel": "",
              "errors": "",
              "key": "email",
              "tags": [],
              "properties": {},
              "conditional": {"show": null, "when": null, "eq": "", "json": ""},
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "type": "email",
              "dataGridLabel": false,
              "input": true,
              "protected": false,
              "persistent": true,
              "refreshOn": "",
              "dbIndex": false,
              "calculateServer": false,
              "overlay": {
                "style": "",
                "left": "",
                "top": "",
                "width": "",
                "height": "",
              },
              "encrypted": false,
              "showCharCount": false,
              "showWordCount": false,
              "allowMultipleMasks": false,
              "addons": [],
              "inputType": "email",
              "inputMask": "",
              "kickbox": {"enabled": false},
              "id": "e6ab65",
              "defaultValue": null,
            },
            {
              "label": "Url",
              "labelPosition": "top",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "prefix": "",
              "suffix": "",
              "widget": {"type": "input"},
              "displayMask": "",
              "applyMaskOn": "change",
              "customClass": "",
              "tabindex": "",
              "autocomplete": "",
              "hidden": false,
              "hideLabel": false,
              "mask": false,
              "autofocus": false,
              "spellcheck": true,
              "disabled": false,
              "tableView": true,
              "modalEdit": false,
              "multiple": false,
              "inputFormat": "plain",
              "truncateMultipleSpaces": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": false,
                "pattern": "",
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "minLength": "",
                "maxLength": "",
                "strictDateValidation": false,
                "multiple": false,
                "unique": false,
              },
              "validateWhenHidden": false,
              "errorLabel": "",
              "errors": "",
              "key": "url",
              "tags": [],
              "properties": {},
              "conditional": {"show": null, "when": null, "eq": "", "json": ""},
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "type": "url",
              "dataGridLabel": false,
              "input": true,
              "protected": false,
              "unique": false,
              "persistent": true,
              "refreshOn": "",
              "dbIndex": false,
              "calculateServer": false,
              "overlay": {
                "style": "",
                "left": "",
                "top": "",
                "width": "",
                "height": "",
              },
              "encrypted": false,
              "showCharCount": false,
              "showWordCount": false,
              "allowMultipleMasks": false,
              "addons": [],
              "inputType": "url",
              "inputMask": "",
              "id": "es2sgv9",
              "defaultValue": null,
            },
            {
              "label": "Phone Number",
              "labelPosition": "top",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "prefix": "",
              "suffix": "",
              "widget": {"type": "input"},
              "inputMask": "(999) 999-9999",
              "displayMask": "",
              "applyMaskOn": "change",
              "allowMultipleMasks": false,
              "customClass": "",
              "tabindex": "",
              "autocomplete": "",
              "hidden": false,
              "hideLabel": false,
              "mask": false,
              "autofocus": false,
              "spellcheck": true,
              "disabled": false,
              "tableView": true,
              "modalEdit": false,
              "multiple": false,
              "inputFormat": "plain",
              "case": "",
              "truncateMultipleSpaces": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": false,
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "strictDateValidation": false,
                "multiple": false,
                "unique": false,
                "minLength": "",
                "maxLength": "",
                "pattern": "",
              },
              "validateWhenHidden": false,
              "errorLabel": "",
              "errors": "",
              "key": "phoneNumber",
              "tags": [],
              "properties": {},
              "conditional": {"show": null, "when": null, "eq": "", "json": ""},
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "type": "phoneNumber",
              "dataGridLabel": false,
              "input": true,
              "protected": false,
              "unique": false,
              "persistent": true,
              "refreshOn": "",
              "dbIndex": false,
              "calculateServer": false,
              "overlay": {
                "style": "",
                "left": "",
                "top": "",
                "width": "",
                "height": "",
              },
              "encrypted": false,
              "showCharCount": false,
              "showWordCount": false,
              "addons": [],
              "inputType": "tel",
              "inputMode": "decimal",
              "id": "eo7p2ig",
              "defaultValue": null,
            },
          ],
          "size": "md",
          "width": 6,
          "currentWidth": 6,
        },
      ],
      "autoAdjust": true,
      "customClass": "",
      "hidden": false,
      "modalEdit": false,
      "key": "datos",
      "tags": [],
      "properties": {},
      "conditional": {"show": null, "when": null, "eq": "", "json": ""},
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "type": "columns",
      "dataGridLabel": false,
      "input": false,
      "placeholder": "",
      "prefix": "",
      "suffix": "",
      "multiple": false,
      "defaultValue": null,
      "protected": false,
      "unique": false,
      "persistent": false,
      "clearOnHide": false,
      "refreshOn": "",
      "redrawOn": "",
      "tableView": false,
      "labelPosition": "top",
      "description": "",
      "errorLabel": "",
      "tooltip": "",
      "hideLabel": false,
      "tabindex": "",
      "disabled": false,
      "autofocus": false,
      "dbIndex": false,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "widget": null,
      "validateOn": "change",
      "validate": {
        "required": false,
        "custom": "",
        "customPrivate": false,
        "strictDateValidation": false,
        "multiple": false,
        "unique": false,
      },
      "overlay": {
        "style": "",
        "left": "",
        "top": "",
        "width": "",
        "height": "",
      },
      "allowCalculateOverride": false,
      "encrypted": false,
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "addons": [],
      "tree": false,
      "lazyLoad": false,
      "id": "eyvti5b",
    },
    {
      "label": "Tabs",
      "components": [
        {"label": "Prospección", "key": "crm", "components": []},
        {
          "label": "OneCRM",
          "key": "sales",
          "components": [
            {
              "label": "Número de Orden",
              "labelPosition": "top",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "prefix": "",
              "suffix": "",
              "widget": {"type": "input"},
              "inputMask": "",
              "displayMask": "",
              "applyMaskOn": "change",
              "allowMultipleMasks": false,
              "customClass": "",
              "tabindex": "",
              "autocomplete": "",
              "hidden": false,
              "hideLabel": false,
              "showWordCount": false,
              "showCharCount": false,
              "mask": false,
              "autofocus": false,
              "spellcheck": true,
              "disabled": false,
              "tableView": true,
              "modalEdit": false,
              "multiple": false,
              "inputFormat": "plain",
              "case": "",
              "truncateMultipleSpaces": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": false,
                "pattern": "",
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "minLength": "",
                "maxLength": "",
                "strictDateValidation": false,
                "multiple": false,
                "unique": false,
              },
              "validateWhenHidden": false,
              "errorLabel": "",
              "errors": "",
              "key": "numeroDeOrden",
              "tags": [],
              "properties": {},
              "conditional": {"show": null, "when": null, "eq": "", "json": ""},
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "type": "textfield",
              "dataGridLabel": false,
              "input": true,
              "protected": false,
              "unique": false,
              "persistent": true,
              "refreshOn": "",
              "dbIndex": false,
              "calculateServer": false,
              "overlay": {
                "style": "",
                "left": "",
                "top": "",
                "width": "",
                "height": "",
              },
              "encrypted": false,
              "addons": [],
              "inputType": "text",
              "id": "eyl71k6",
              "defaultValue": "",
            },
          ],
        },
        {
          "label": "Deployment",
          "key": "deployment",
          "components": [
            {
              "label": "Orden de instalacion",
              "labelPosition": "top",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "prefix": "",
              "suffix": "",
              "widget": {"type": "input"},
              "inputMask": "",
              "displayMask": "",
              "applyMaskOn": "change",
              "allowMultipleMasks": false,
              "customClass": "",
              "tabindex": "",
              "autocomplete": "",
              "hidden": false,
              "hideLabel": false,
              "showWordCount": false,
              "showCharCount": false,
              "mask": false,
              "autofocus": false,
              "spellcheck": true,
              "disabled": false,
              "tableView": true,
              "modalEdit": false,
              "multiple": false,
              "inputFormat": "plain",
              "case": "",
              "truncateMultipleSpaces": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": false,
                "pattern": "",
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "minLength": "",
                "maxLength": "",
                "strictDateValidation": false,
                "multiple": false,
                "unique": false,
              },
              "validateWhenHidden": false,
              "errorLabel": "",
              "errors": "",
              "key": "ordenDeInstalacion",
              "tags": [],
              "properties": {},
              "conditional": {"show": null, "when": null, "eq": "", "json": ""},
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "type": "textfield",
              "dataGridLabel": false,
              "input": true,
              "protected": false,
              "unique": false,
              "persistent": true,
              "refreshOn": "",
              "dbIndex": false,
              "calculateServer": false,
              "overlay": {
                "style": "",
                "left": "",
                "top": "",
                "width": "",
                "height": "",
              },
              "encrypted": false,
              "addons": [],
              "inputType": "text",
              "id": "e4btsw7",
              "defaultValue": "",
            },
          ],
        },
        {"label": "QA/QC", "key": "qa", "components": []},
      ],
      "customClass": "",
      "hidden": false,
      "verticalLayout": false,
      "modalEdit": false,
      "key": "tabs",
      "tags": [],
      "properties": {},
      "conditional": {"show": null, "when": null, "eq": "", "json": ""},
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "type": "tabs",
      "dataGridLabel": false,
      "input": false,
      "placeholder": "",
      "prefix": "",
      "suffix": "",
      "multiple": false,
      "defaultValue": null,
      "protected": false,
      "unique": false,
      "persistent": false,
      "clearOnHide": true,
      "refreshOn": "",
      "redrawOn": "",
      "tableView": false,
      "labelPosition": "top",
      "description": "",
      "errorLabel": "",
      "tooltip": "",
      "hideLabel": false,
      "tabindex": "",
      "disabled": false,
      "autofocus": false,
      "dbIndex": false,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "widget": null,
      "validateOn": "change",
      "validate": {
        "required": false,
        "custom": "",
        "customPrivate": false,
        "strictDateValidation": false,
        "multiple": false,
        "unique": false,
      },
      "overlay": {
        "style": "",
        "left": "",
        "top": "",
        "width": "",
        "height": "",
      },
      "allowCalculateOverride": false,
      "encrypted": false,
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "addons": [],
      "tree": false,
      "lazyLoad": false,
      "id": "ewegxs8",
    },
    {
      "collapsible": false,
      "key": "panel",
      "type": "panel",
      "label": "Panel",
      "input": false,
      "tableView": false,
      "components": [
        {
          "label": "Current Name",
          "applyMaskOn": "change",
          "tableView": true,
          "validateWhenHidden": false,
          "key": "currentName",
          "type": "textfield",
          "input": true,
        },
      ],
    },
    {
      "type": "button",
      "label": "Submit",
      "key": "submit",
      "size": "md",
      "block": false,
      "action": "submit",
      "disableOnInvalid": true,
      "theme": "primary",
      "id": "ekvpr0m",
      "input": true,
      "placeholder": "",
      "prefix": "",
      "customClass": "",
      "suffix": "",
      "multiple": false,
      "defaultValue": null,
      "protected": false,
      "unique": false,
      "persistent": false,
      "hidden": false,
      "clearOnHide": true,
      "refreshOn": "",
      "redrawOn": "",
      "tableView": false,
      "modalEdit": false,
      "dataGridLabel": true,
      "labelPosition": "top",
      "description": "",
      "errorLabel": "",
      "tooltip": "",
      "hideLabel": false,
      "tabindex": "",
      "disabled": false,
      "autofocus": false,
      "dbIndex": false,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "widget": {"type": "input"},
      "attributes": {},
      "validateOn": "change",
      "validate": {
        "required": false,
        "custom": "",
        "customPrivate": false,
        "strictDateValidation": false,
        "multiple": false,
        "unique": false,
      },
      "conditional": {"show": null, "when": null, "eq": ""},
      "overlay": {
        "style": "",
        "left": "",
        "top": "",
        "width": "",
        "height": "",
      },
      "allowCalculateOverride": false,
      "encrypted": false,
      "showCharCount": false,
      "showWordCount": false,
      "properties": {},
      "allowMultipleMasks": false,
      "addons": [],
      "leftIcon": "",
      "rightIcon": "",
    },
  ],
};
