import 'package:flutter/material.dart';
import 'package:formio/formio.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'FormIO Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF6366F1),
          brightness: Brightness.light,
        ),
        useMaterial3: true,
        cardTheme: const CardThemeData(
          elevation: 2,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.all(Radius.circular(12)),
          ),
        ),
      ),
      debugShowCheckedModeBanner: false,
      home: const MyHomePage(title: 'Modern FormIO Demo'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late FormModel form;
  int index = 0;

  @override
  void initState() {
    super.initState();
    form = FormModel.fromJson(jsonData);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Container(
        padding: EdgeInsets.all(20),
        child: FormRenderer(
          form: form,
          onChanged: (value) {
            setState(() {});
          },
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {},
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

Map<String, dynamic> jsonData = {
  '_id': '64a7b1f4e4b0c9001cfa5f3d',
  'path': 'registration',
  'title': 'Modern Registration Form',
  'name': 'registration',
  "components": [
    {
      "title": "Page 1",
      "label": "Page 1",
      "type": "panel",
      "key": "page1",
      "components": [
        {
          "label": "LOAD PICTURE FROM SERVER",
          "action": "submit",
          "showValidations": false,
          "theme": "primary",
          "size": "md",
          "block": false,
          "leftIcon": "",
          "rightIcon": "",
          "shortcut": "",
          "description": "",
          "tooltip": "",
          "customClass": "",
          "tabindex": "",
          "disableOnInvalid": false,
          "hidden": false,
          "autofocus": false,
          "disabled": false,
          "tableView": false,
          "modalEdit": false,
          "key": "loadPictureFromServer",
          "tags": [],
          "properties": {},
          "conditional": {"show": null, "when": null, "eq": "", "json": ""},
          "customConditional": "",
          "logic": [],
          "attributes": {},
          "overlay": {
            "style": "",
            "page": "",
            "left": "",
            "top": "",
            "width": "",
            "height": "",
          },
          "type": "button",
          "hideLabel": false,
          "input": true,
          "placeholder": "",
          "prefix": "",
          "suffix": "",
          "multiple": false,
          "defaultValue": null,
          "protected": false,
          "unique": false,
          "persistent": false,
          "clearOnHide": true,
          "refreshOn": "",
          "redrawOn": "",
          "dataGridLabel": true,
          "labelPosition": "top",
          "errorLabel": "",
          "dbIndex": false,
          "customDefaultValue": "",
          "calculateValue": "",
          "calculateServer": false,
          "widget": {"type": "input"},
          "validateOn": "change",
          "validate": {
            "required": false,
            "custom": "",
            "customPrivate": false,
            "strictDateValidation": false,
            "multiple": false,
            "unique": false,
          },
          "allowCalculateOverride": false,
          "encrypted": false,
          "showCharCount": false,
          "showWordCount": false,
          "allowMultipleMasks": false,
          "addons": [],
          "id": "e2rua2c",
          "saveOnEnter": false,
        },
        {
          "html": "",
          "label": "Content",
          "customClass": "",
          "refreshOnChange": false,
          "hidden": false,
          "modalEdit": false,
          "key": "content",
          "tags": [],
          "properties": {},
          "conditional": {"show": null, "when": null, "eq": "", "json": ""},
          "customConditional": "",
          "logic": [],
          "attributes": {},
          "type": "content",
          "dataGridLabel": false,
          "input": false,
          "placeholder": "",
          "prefix": "",
          "suffix": "",
          "multiple": false,
          "defaultValue": null,
          "protected": false,
          "unique": false,
          "persistent": true,
          "clearOnHide": true,
          "refreshOn": "",
          "redrawOn": "",
          "tableView": false,
          "labelPosition": "top",
          "description": "",
          "errorLabel": "",
          "tooltip": "",
          "hideLabel": false,
          "tabindex": "",
          "disabled": false,
          "autofocus": false,
          "dbIndex": false,
          "customDefaultValue": "",
          "calculateValue": "",
          "calculateServer": false,
          "widget": null,
          "validateOn": "change",
          "validate": {
            "required": false,
            "custom": "",
            "customPrivate": false,
            "strictDateValidation": false,
            "multiple": false,
            "unique": false,
          },
          "overlay": {
            "style": "",
            "left": "",
            "top": "",
            "width": "",
            "height": "",
          },
          "allowCalculateOverride": false,
          "encrypted": false,
          "showCharCount": false,
          "showWordCount": false,
          "allowMultipleMasks": false,
          "addons": [],
          "id": "edg5d8",
        },
        {
          "label": "Columns",
          "columns": [
            {
              "components": [
                {
                  "label": "Text Field",
                  "labelPosition": "top",
                  "placeholder": "",
                  "description": "",
                  "tooltip": "",
                  "prefix": "",
                  "suffix": "",
                  "widget": {"type": "input"},
                  "inputMask": "",
                  "displayMask": "",
                  "applyMaskOn": "change",
                  "allowMultipleMasks": false,
                  "customClass": "",
                  "tabindex": "",
                  "autocomplete": "",
                  "hidden": false,
                  "hideLabel": false,
                  "showWordCount": false,
                  "showCharCount": false,
                  "mask": false,
                  "autofocus": false,
                  "spellcheck": true,
                  "disabled": false,
                  "tableView": true,
                  "modalEdit": false,
                  "multiple": false,
                  "inputFormat": "plain",
                  "case": "",
                  "truncateMultipleSpaces": false,
                  "redrawOn": "",
                  "clearOnHide": true,
                  "customDefaultValue": "",
                  "calculateValue": "",
                  "allowCalculateOverride": false,
                  "validateOn": "change",
                  "validate": {
                    "required": false,
                    "pattern": "",
                    "customMessage": "",
                    "custom": "",
                    "customPrivate": false,
                    "json": "",
                    "minLength": "",
                    "maxLength": "",
                    "strictDateValidation": false,
                    "multiple": false,
                    "unique": false,
                  },
                  "validateWhenHidden": false,
                  "errorLabel": "",
                  "errors": "",
                  "key": "textField",
                  "tags": [],
                  "properties": {},
                  "conditional": {
                    "show": null,
                    "when": null,
                    "eq": "",
                    "json": "",
                  },
                  "customConditional": "",
                  "logic": [],
                  "attributes": {},
                  "type": "textfield",
                  "dataGridLabel": false,
                  "input": true,
                  "protected": false,
                  "unique": false,
                  "persistent": true,
                  "refreshOn": "",
                  "dbIndex": false,
                  "calculateServer": false,
                  "overlay": {
                    "style": "",
                    "left": "",
                    "top": "",
                    "width": "",
                    "height": "",
                  },
                  "encrypted": false,
                  "addons": [],
                  "inputType": "text",
                  "id": "et7gh16",
                  "defaultValue": null,
                },
                {
                  "label": "Number",
                  "labelPosition": "top",
                  "placeholder": "",
                  "description": "",
                  "tooltip": "",
                  "prefix": "",
                  "suffix": "",
                  "widget": {"type": "input"},
                  "displayMask": "",
                  "applyMaskOn": "change",
                  "customClass": "",
                  "tabindex": "",
                  "autocomplete": "",
                  "hidden": false,
                  "hideLabel": false,
                  "mask": false,
                  "autofocus": false,
                  "disabled": false,
                  "tableView": false,
                  "modalEdit": false,
                  "multiple": false,
                  "delimiter": false,
                  "requireDecimal": false,
                  "inputFormat": "plain",
                  "truncateMultipleSpaces": false,
                  "redrawOn": "",
                  "clearOnHide": true,
                  "customDefaultValue": "",
                  "calculateValue": "",
                  "allowCalculateOverride": false,
                  "validateOn": "change",
                  "validate": {
                    "required": false,
                    "customMessage": "",
                    "custom": "",
                    "customPrivate": false,
                    "json": "",
                    "min": "",
                    "max": "",
                    "strictDateValidation": false,
                    "multiple": false,
                    "unique": false,
                    "step": "any",
                    "integer": "",
                  },
                  "validateWhenHidden": false,
                  "errorLabel": "",
                  "errors": "",
                  "key": "number",
                  "tags": [],
                  "properties": {},
                  "conditional": {
                    "show": null,
                    "when": null,
                    "eq": "",
                    "json": "",
                  },
                  "customConditional": "",
                  "logic": [],
                  "attributes": {},
                  "type": "number",
                  "dataGridLabel": false,
                  "input": true,
                  "protected": false,
                  "unique": false,
                  "persistent": true,
                  "refreshOn": "",
                  "dbIndex": false,
                  "calculateServer": false,
                  "overlay": {
                    "style": "",
                    "left": "",
                    "top": "",
                    "width": "",
                    "height": "",
                  },
                  "encrypted": false,
                  "showCharCount": false,
                  "showWordCount": false,
                  "allowMultipleMasks": false,
                  "addons": [],
                  "id": "epe16kb",
                  "defaultValue": null,
                },
                {
                  "label": "Select Boxes (have birthday?)",
                  "labelPosition": "top",
                  "optionsLabelPosition": "right",
                  "description": "",
                  "tooltip": "",
                  "customClass": "",
                  "tabindex": "",
                  "inline": false,
                  "hidden": false,
                  "hideLabel": false,
                  "autofocus": false,
                  "disabled": false,
                  "tableView": false,
                  "modalEdit": false,
                  "dataSrc": "values",
                  "defaultValue": {"yes": false, "no": false},
                  "values": [
                    {"label": "Yes", "value": "yes", "shortcut": "Y"},
                    {"label": "No", "value": "no", "shortcut": "N"},
                  ],
                  "valueProperty": "",
                  "clearOnHide": true,
                  "customDefaultValue": "",
                  "calculateValue": "",
                  "allowCalculateOverride": false,
                  "validate": {
                    "required": true,
                    "onlyAvailableItems": false,
                    "customMessage": "",
                    "custom": "",
                    "customPrivate": false,
                    "json": "",
                    "strictDateValidation": false,
                    "multiple": false,
                    "unique": false,
                  },
                  "validateWhenHidden": false,
                  "errorLabel": "",
                  "minSelectedCountMessage": "",
                  "maxSelectedCountMessage": "",
                  "errors": "",
                  "key": "selectBoxes",
                  "tags": [],
                  "properties": {},
                  "conditional": {
                    "show": null,
                    "when": null,
                    "eq": "",
                    "json": "",
                  },
                  "customConditional": "",
                  "logic": [],
                  "attributes": {},
                  "type": "selectboxes",
                  "dataGridLabel": false,
                  "data": {"url": ""},
                  "template": "<span>{{ item.label }}</span>",
                  "ignoreCache": false,
                  "redrawOn": "",
                  "input": true,
                  "inputType": "checkbox",
                  "placeholder": "",
                  "prefix": "",
                  "suffix": "",
                  "multiple": false,
                  "protected": false,
                  "unique": false,
                  "persistent": true,
                  "refreshOn": "",
                  "dbIndex": false,
                  "calculateServer": false,
                  "widget": null,
                  "validateOn": "change",
                  "overlay": {
                    "style": "",
                    "left": "",
                    "top": "",
                    "width": "",
                    "height": "",
                  },
                  "encrypted": false,
                  "showCharCount": false,
                  "showWordCount": false,
                  "allowMultipleMasks": false,
                  "addons": [],
                  "authenticate": false,
                  "fieldSet": false,
                  "id": "e2ul4lh",
                },
                {
                  "label": "Date / Time",
                  "labelPosition": "top",
                  "displayInTimezone": "viewer",
                  "useLocaleSettings": false,
                  "allowInput": true,
                  "format": "yyyy-MM-dd hh:mm a",
                  "placeholder": "",
                  "description": "",
                  "tooltip": "",
                  "customClass": "",
                  "tabindex": "",
                  "hidden": false,
                  "hideLabel": false,
                  "autofocus": false,
                  "disabled": false,
                  "tableView": false,
                  "modalEdit": false,
                  "shortcutButtons": [],
                  "enableDate": true,
                  "datePicker": {
                    "disable": "",
                    "disableFunction": "",
                    "disableWeekends": false,
                    "disableWeekdays": false,
                    "minDate": null,
                    "maxDate": null,
                    "showWeeks": true,
                    "startingDay": 0,
                    "initDate": "",
                    "minMode": "day",
                    "maxMode": "year",
                    "yearRows": 4,
                    "yearColumns": 5,
                  },
                  "enableTime": true,
                  "timePicker": {
                    "showMeridian": true,
                    "hourStep": 1,
                    "minuteStep": 1,
                    "readonlyInput": false,
                    "mousewheel": true,
                    "arrowkeys": true,
                  },
                  "multiple": false,
                  "defaultValue": "",
                  "defaultDate": "",
                  "customOptions": {},
                  "redrawOn": "",
                  "clearOnHide": true,
                  "customDefaultValue": "",
                  "calculateValue": "",
                  "allowCalculateOverride": false,
                  "validateOn": "change",
                  "validate": {
                    "required": false,
                    "customMessage": "",
                    "custom": "",
                    "customPrivate": false,
                    "json": "",
                    "strictDateValidation": false,
                    "multiple": false,
                    "unique": false,
                  },
                  "enableMinDateInput": false,
                  "enableMaxDateInput": false,
                  "validateWhenHidden": false,
                  "errorLabel": "",
                  "errors": "",
                  "key": "dateTime",
                  "tags": [],
                  "properties": {},
                  "conditional": {
                    "show": null,
                    "when": null,
                    "eq": "",
                    "json": "",
                  },
                  "customConditional": "",
                  "logic": [],
                  "attributes": {},
                  "type": "datetime",
                  "timezone": "",
                  "dataGridLabel": false,
                  "input": true,
                  "prefix": "",
                  "suffix": "",
                  "protected": false,
                  "unique": false,
                  "persistent": true,
                  "refreshOn": "",
                  "dbIndex": false,
                  "calculateServer": false,
                  "widget": {
                    "type": "calendar",
                    "displayInTimezone": "viewer",
                    "locale": "en-US",
                    "useLocaleSettings": false,
                    "allowInput": true,
                    "mode": "single",
                    "enableTime": true,
                    "noCalendar": false,
                    "format": "yyyy-MM-dd hh:mm a",
                    "hourIncrement": 1,
                    "minuteIncrement": 1,
                    "time_24hr": false,
                    "minDate": null,
                    "disabledDates": "",
                    "disableWeekends": false,
                    "disableWeekdays": false,
                    "disableFunction": "",
                    "maxDate": null,
                  },
                  "overlay": {
                    "style": "",
                    "left": "",
                    "top": "",
                    "width": "",
                    "height": "",
                  },
                  "encrypted": false,
                  "showCharCount": false,
                  "showWordCount": false,
                  "allowMultipleMasks": false,
                  "addons": [],
                  "datepickerMode": "day",
                  "id": "eh85nsk",
                },
                {
                  "label": "Phone Number",
                  "labelPosition": "top",
                  "placeholder": "",
                  "description": "",
                  "tooltip": "",
                  "prefix": "",
                  "suffix": "",
                  "widget": {"type": "input"},
                  "inputMask": "(999) 999-9999",
                  "displayMask": "",
                  "applyMaskOn": "change",
                  "allowMultipleMasks": false,
                  "customClass": "",
                  "tabindex": "",
                  "autocomplete": "",
                  "hidden": false,
                  "hideLabel": false,
                  "mask": false,
                  "autofocus": false,
                  "spellcheck": true,
                  "disabled": false,
                  "tableView": true,
                  "modalEdit": false,
                  "multiple": false,
                  "inputFormat": "plain",
                  "case": "",
                  "truncateMultipleSpaces": false,
                  "redrawOn": "",
                  "clearOnHide": true,
                  "customDefaultValue": "",
                  "calculateValue": "",
                  "allowCalculateOverride": false,
                  "validateOn": "change",
                  "validate": {
                    "required": false,
                    "customMessage": "",
                    "custom": "",
                    "customPrivate": false,
                    "json": "",
                    "strictDateValidation": false,
                    "multiple": false,
                    "unique": false,
                    "minLength": "",
                    "maxLength": "",
                    "pattern": "",
                  },
                  "validateWhenHidden": false,
                  "errorLabel": "",
                  "errors": "",
                  "key": "phoneNumber",
                  "tags": [],
                  "properties": {},
                  "conditional": {
                    "show": true,
                    "when": "selectBoxes",
                    "eq": "yes",
                    "json": "",
                  },
                  "customConditional": "",
                  "logic": [],
                  "attributes": {},
                  "type": "phoneNumber",
                  "dataGridLabel": false,
                  "input": true,
                  "protected": false,
                  "unique": false,
                  "persistent": true,
                  "refreshOn": "",
                  "dbIndex": false,
                  "calculateServer": false,
                  "overlay": {
                    "style": "",
                    "left": "",
                    "top": "",
                    "width": "",
                    "height": "",
                  },
                  "encrypted": false,
                  "showCharCount": false,
                  "showWordCount": false,
                  "addons": [],
                  "inputType": "tel",
                  "inputMode": "decimal",
                  "id": "e7s4fed",
                  "inputMaskPlaceholderChar": "",
                  "defaultValue": "",
                },
                {
                  "label": "Currency",
                  "labelPosition": "top",
                  "placeholder": "",
                  "description": "",
                  "tooltip": "",
                  "prefix": "",
                  "suffix": "",
                  "widget": {"type": "input"},
                  "displayMask": "",
                  "applyMaskOn": "change",
                  "customClass": "",
                  "tabindex": "",
                  "autocomplete": "",
                  "hidden": false,
                  "hideLabel": false,
                  "mask": false,
                  "autofocus": false,
                  "spellcheck": true,
                  "disabled": false,
                  "tableView": false,
                  "modalEdit": false,
                  "multiple": false,
                  "currency": "USD",
                  "inputFormat": "plain",
                  "case": "",
                  "truncateMultipleSpaces": false,
                  "redrawOn": "",
                  "clearOnHide": true,
                  "customDefaultValue": "",
                  "calculateValue": "",
                  "allowCalculateOverride": false,
                  "validateOn": "change",
                  "validate": {
                    "required": false,
                    "customMessage": "",
                    "custom": "",
                    "customPrivate": false,
                    "json": "",
                    "strictDateValidation": false,
                    "multiple": false,
                    "unique": false,
                    "min": "",
                    "max": "",
                    "step": "any",
                    "integer": "",
                  },
                  "validateWhenHidden": false,
                  "errorLabel": "",
                  "errors": "",
                  "key": "currency",
                  "tags": [],
                  "properties": {},
                  "conditional": {
                    "show": null,
                    "when": null,
                    "eq": "",
                    "json": "",
                  },
                  "customConditional": "",
                  "logic": [],
                  "attributes": {},
                  "type": "currency",
                  "dataGridLabel": false,
                  "input": true,
                  "protected": false,
                  "unique": false,
                  "persistent": true,
                  "refreshOn": "",
                  "dbIndex": false,
                  "calculateServer": false,
                  "overlay": {
                    "style": "",
                    "left": "",
                    "top": "",
                    "width": "",
                    "height": "",
                  },
                  "encrypted": false,
                  "showCharCount": false,
                  "showWordCount": false,
                  "allowMultipleMasks": false,
                  "addons": [],
                  "delimiter": true,
                  "id": "e135u6e",
                  "defaultValue": null,
                },
              ],
              "width": 6,
              "offset": 0,
              "push": 0,
              "pull": 0,
              "size": "lg",
              "currentWidth": 6,
            },
            {
              "components": [
                {
                  "label": "Text Area",
                  "labelPosition": "top",
                  "placeholder": "",
                  "description": "",
                  "tooltip": "",
                  "prefix": "",
                  "suffix": "",
                  "widget": {"type": "input"},
                  "displayMask": "",
                  "applyMaskOn": "change",
                  "editor": "",
                  "autoExpand": false,
                  "customClass": "",
                  "tabindex": "",
                  "autocomplete": "",
                  "hidden": false,
                  "hideLabel": false,
                  "showWordCount": false,
                  "showCharCount": false,
                  "autofocus": false,
                  "spellcheck": true,
                  "disabled": false,
                  "tableView": true,
                  "modalEdit": false,
                  "multiple": false,
                  "inputFormat": "html",
                  "case": "",
                  "truncateMultipleSpaces": false,
                  "redrawOn": "",
                  "clearOnHide": true,
                  "customDefaultValue": "",
                  "calculateValue": "",
                  "allowCalculateOverride": false,
                  "validateOn": "change",
                  "validate": {
                    "required": false,
                    "pattern": "",
                    "customMessage": "",
                    "custom": "",
                    "customPrivate": false,
                    "json": "",
                    "minLength": "",
                    "maxLength": "",
                    "minWords": "",
                    "maxWords": "",
                    "strictDateValidation": false,
                    "multiple": false,
                    "unique": false,
                  },
                  "validateWhenHidden": false,
                  "errorLabel": "",
                  "errors": "",
                  "key": "textArea",
                  "tags": [],
                  "properties": {},
                  "conditional": {
                    "show": null,
                    "when": null,
                    "eq": "",
                    "json": "",
                  },
                  "customConditional": "",
                  "logic": [],
                  "attributes": {},
                  "type": "textarea",
                  "rows": 3,
                  "wysiwyg": false,
                  "dataGridLabel": false,
                  "input": true,
                  "protected": false,
                  "unique": false,
                  "persistent": true,
                  "refreshOn": "",
                  "dbIndex": false,
                  "calculateServer": false,
                  "overlay": {
                    "style": "",
                    "left": "",
                    "top": "",
                    "width": "",
                    "height": "",
                  },
                  "encrypted": false,
                  "allowMultipleMasks": false,
                  "addons": [],
                  "mask": false,
                  "inputType": "text",
                  "inputMask": "",
                  "fixedSize": true,
                  "id": "eo635p7",
                  "defaultValue": null,
                },
                {
                  "label": "Select",
                  "labelPosition": "top",
                  "widget": "choicesjs",
                  "placeholder": "",
                  "description": "",
                  "tooltip": "",
                  "customClass": "",
                  "tabindex": "",
                  "hidden": false,
                  "hideLabel": false,
                  "uniqueOptions": false,
                  "autofocus": false,
                  "disabled": false,
                  "tableView": true,
                  "modalEdit": false,
                  "multiple": false,
                  "dataSrc": "values",
                  "data": {
                    "values": [
                      {"label": "Ecuador", "value": "ecuador"},
                      {"label": "Ethiopia", "value": "ethiopia"},
                      {"label": "Mexico", "value": "mexico"},
                      {"label": "Japan", "value": "japan"},
                    ],
                    "resource": "",
                    "url": "",
                    "json": "",
                    "custom": "",
                  },
                  "dataType": "string",
                  "idPath": "id",
                  "valueProperty": "",
                  "template": "<span>{{ item.label }}</span>",
                  "refreshOn": "",
                  "refreshOnBlur": "",
                  "clearOnRefresh": false,
                  "searchEnabled": true,
                  "selectThreshold": 0.3,
                  "readOnlyValue": false,
                  "customOptions": {},
                  "useExactSearch": false,
                  "clearOnHide": true,
                  "customDefaultValue": "",
                  "calculateValue": "",
                  "allowCalculateOverride": false,
                  "validateOn": "change",
                  "validate": {
                    "required": false,
                    "onlyAvailableItems": false,
                    "customMessage": "",
                    "custom": "",
                    "customPrivate": false,
                    "json": "",
                    "strictDateValidation": false,
                    "multiple": false,
                    "unique": false,
                  },
                  "unique": false,
                  "validateWhenHidden": false,
                  "errorLabel": "",
                  "errors": "",
                  "key": "select",
                  "tags": [],
                  "properties": {},
                  "conditional": {
                    "show": null,
                    "when": null,
                    "eq": "",
                    "json": "",
                  },
                  "customConditional": "",
                  "logic": [],
                  "attributes": {},
                  "overlay": {
                    "style": "",
                    "page": "",
                    "left": "",
                    "top": "",
                    "width": "",
                    "height": "",
                  },
                  "type": "select",
                  "indexeddb": {"filter": {}},
                  "dataGridLabel": false,
                  "lazyLoad": true,
                  "selectFields": "",
                  "searchField": "",
                  "searchDebounce": 0.3,
                  "minSearch": 0,
                  "filter": "",
                  "limit": 100,
                  "ignoreCache": false,
                  "redrawOn": "",
                  "input": true,
                  "prefix": "",
                  "suffix": "",
                  "protected": false,
                  "persistent": true,
                  "dbIndex": false,
                  "calculateServer": false,
                  "encrypted": false,
                  "showCharCount": false,
                  "showWordCount": false,
                  "allowMultipleMasks": false,
                  "addons": [],
                  "authenticate": false,
                  "fuseOptions": {"include": "score", "threshold": 0.3},
                  "id": "e2ayslsj",
                  "defaultValue": "",
                },
                {
                  "label": "Checkbox",
                  "description": "",
                  "tooltip": "",
                  "shortcut": "",
                  "inputType": "checkbox",
                  "customClass": "",
                  "tabindex": "",
                  "hidden": false,
                  "hideLabel": false,
                  "autofocus": false,
                  "disabled": false,
                  "tableView": false,
                  "modalEdit": false,
                  "redrawOn": "",
                  "clearOnHide": true,
                  "customDefaultValue": "",
                  "calculateValue": "",
                  "allowCalculateOverride": false,
                  "validate": {
                    "required": false,
                    "customMessage": "",
                    "custom": "",
                    "customPrivate": false,
                    "json": "",
                    "strictDateValidation": false,
                    "multiple": false,
                    "unique": false,
                  },
                  "validateWhenHidden": false,
                  "errorLabel": "",
                  "errors": "",
                  "key": "checkbox",
                  "tags": [],
                  "properties": {},
                  "conditional": {
                    "show": null,
                    "when": null,
                    "eq": "",
                    "json": "",
                  },
                  "customConditional": "",
                  "logic": [],
                  "attributes": {},
                  "type": "checkbox",
                  "name": "",
                  "value": "",
                  "dataGridLabel": true,
                  "input": true,
                  "placeholder": "",
                  "prefix": "",
                  "suffix": "",
                  "multiple": false,
                  "protected": false,
                  "unique": false,
                  "persistent": true,
                  "refreshOn": "",
                  "labelPosition": "right",
                  "dbIndex": false,
                  "calculateServer": false,
                  "widget": null,
                  "validateOn": "change",
                  "overlay": {
                    "style": "",
                    "left": "",
                    "top": "",
                    "width": "",
                    "height": "",
                  },
                  "encrypted": false,
                  "showCharCount": false,
                  "showWordCount": false,
                  "allowMultipleMasks": false,
                  "addons": [],
                  "id": "enov86h",
                  "defaultValue": null,
                },
                {
                  "label": "Radio",
                  "labelPosition": "top",
                  "optionsLabelPosition": "right",
                  "description": "",
                  "tooltip": "",
                  "customClass": "",
                  "tabindex": "",
                  "inline": false,
                  "hidden": false,
                  "hideLabel": false,
                  "autofocus": false,
                  "disabled": false,
                  "tableView": false,
                  "modalEdit": false,
                  "dataSrc": "values",
                  "values": [
                    {"label": "1", "value": "1", "shortcut": ""},
                    {"label": "2", "value": "2", "shortcut": ""},
                    {"label": "3", "value": "3", "shortcut": ""},
                  ],
                  "dataType": "",
                  "valueProperty": "",
                  "clearOnHide": true,
                  "customDefaultValue": "",
                  "calculateValue": "",
                  "allowCalculateOverride": false,
                  "validate": {
                    "required": false,
                    "onlyAvailableItems": false,
                    "customMessage": "",
                    "custom": "",
                    "customPrivate": false,
                    "json": "",
                    "strictDateValidation": false,
                    "multiple": false,
                    "unique": false,
                  },
                  "validateWhenHidden": false,
                  "errorLabel": "",
                  "errors": "",
                  "key": "radio",
                  "tags": [],
                  "properties": {},
                  "conditional": {
                    "show": null,
                    "when": null,
                    "eq": "",
                    "json": "",
                  },
                  "customConditional": "",
                  "logic": [],
                  "attributes": {},
                  "overlay": {
                    "style": "",
                    "page": "",
                    "left": "",
                    "top": "",
                    "width": "",
                    "height": "",
                  },
                  "type": "radio",
                  "dataGridLabel": false,
                  "data": {"url": ""},
                  "template": "<span>{{ item.label }}</span>",
                  "ignoreCache": false,
                  "redrawOn": "",
                  "input": true,
                  "placeholder": "",
                  "prefix": "",
                  "suffix": "",
                  "multiple": false,
                  "protected": false,
                  "unique": false,
                  "persistent": true,
                  "refreshOn": "",
                  "dbIndex": false,
                  "calculateServer": false,
                  "widget": null,
                  "validateOn": "change",
                  "encrypted": false,
                  "showCharCount": false,
                  "showWordCount": false,
                  "allowMultipleMasks": false,
                  "addons": [],
                  "authenticate": false,
                  "inputType": "radio",
                  "fieldSet": false,
                  "id": "ebu9chd",
                  "defaultValue": "",
                },
                {
                  "label": "Url",
                  "labelPosition": "top",
                  "placeholder": "",
                  "description": "",
                  "tooltip": "",
                  "prefix": "",
                  "suffix": "",
                  "widget": {"type": "input"},
                  "displayMask": "",
                  "applyMaskOn": "change",
                  "customClass": "",
                  "tabindex": "",
                  "autocomplete": "",
                  "hidden": false,
                  "hideLabel": false,
                  "mask": false,
                  "autofocus": false,
                  "spellcheck": true,
                  "disabled": false,
                  "tableView": true,
                  "modalEdit": false,
                  "multiple": false,
                  "inputFormat": "plain",
                  "truncateMultipleSpaces": false,
                  "redrawOn": "",
                  "clearOnHide": true,
                  "customDefaultValue": "",
                  "calculateValue": "",
                  "allowCalculateOverride": false,
                  "validateOn": "change",
                  "validate": {
                    "required": false,
                    "pattern": "",
                    "customMessage": "",
                    "custom": "",
                    "customPrivate": false,
                    "json": "",
                    "minLength": "",
                    "maxLength": "",
                    "strictDateValidation": false,
                    "multiple": false,
                    "unique": false,
                  },
                  "validateWhenHidden": false,
                  "errorLabel": "",
                  "errors": "",
                  "key": "url",
                  "tags": [],
                  "properties": {},
                  "conditional": {
                    "show": null,
                    "when": null,
                    "eq": "",
                    "json": "",
                  },
                  "customConditional": "",
                  "logic": [],
                  "attributes": {},
                  "type": "url",
                  "dataGridLabel": false,
                  "input": true,
                  "protected": false,
                  "unique": false,
                  "persistent": true,
                  "refreshOn": "",
                  "dbIndex": false,
                  "calculateServer": false,
                  "overlay": {
                    "style": "",
                    "left": "",
                    "top": "",
                    "width": "",
                    "height": "",
                  },
                  "encrypted": false,
                  "showCharCount": false,
                  "showWordCount": false,
                  "allowMultipleMasks": false,
                  "addons": [],
                  "inputType": "url",
                  "inputMask": "",
                  "id": "eee7ckr",
                  "defaultValue": null,
                },
                {
                  "label": "Time",
                  "labelPosition": "top",
                  "inputType": "time",
                  "description": "",
                  "tooltip": "",
                  "customClass": "",
                  "tabindex": "",
                  "hidden": false,
                  "hideLabel": false,
                  "autofocus": false,
                  "disabled": false,
                  "tableView": true,
                  "modalEdit": false,
                  "multiple": false,
                  "dataFormat": "HH:mm:ss",
                  "redrawOn": "",
                  "clearOnHide": true,
                  "customDefaultValue": "",
                  "calculateValue": "",
                  "allowCalculateOverride": false,
                  "validateOn": "change",
                  "validate": {
                    "required": false,
                    "customMessage": "",
                    "custom": "",
                    "customPrivate": false,
                    "json": "",
                    "strictDateValidation": false,
                    "multiple": false,
                    "unique": false,
                    "minLength": "",
                    "maxLength": "",
                    "pattern": "",
                  },
                  "validateWhenHidden": false,
                  "errorLabel": "",
                  "errors": "",
                  "key": "time",
                  "tags": [],
                  "properties": {},
                  "conditional": {
                    "show": null,
                    "when": null,
                    "eq": "",
                    "json": "",
                  },
                  "customConditional": "",
                  "logic": [],
                  "attributes": {},
                  "type": "time",
                  "format": "HH:mm",
                  "dataGridLabel": false,
                  "input": true,
                  "placeholder": "",
                  "prefix": "",
                  "suffix": "",
                  "protected": false,
                  "unique": false,
                  "persistent": true,
                  "refreshOn": "",
                  "dbIndex": false,
                  "calculateServer": false,
                  "widget": {"type": "input"},
                  "overlay": {
                    "style": "",
                    "left": "",
                    "top": "",
                    "width": "",
                    "height": "",
                  },
                  "encrypted": false,
                  "showCharCount": false,
                  "showWordCount": false,
                  "allowMultipleMasks": false,
                  "addons": [],
                  "mask": false,
                  "inputFormat": "plain",
                  "inputMask": "99:99",
                  "displayMask": "",
                  "spellcheck": true,
                  "truncateMultipleSpaces": false,
                  "id": "ercv3bd",
                  "defaultValue": null,
                },
              ],
              "width": 4,
              "offset": 0,
              "push": 0,
              "pull": 0,
              "size": "md",
              "currentWidth": 4,
            },
            {
              "components": [
                {
                  "label": "Email",
                  "labelPosition": "top",
                  "placeholder": "",
                  "description": "",
                  "tooltip": "",
                  "prefix": "",
                  "suffix": "",
                  "widget": {"type": "input"},
                  "displayMask": "",
                  "applyMaskOn": "change",
                  "customClass": "",
                  "tabindex": "",
                  "autocomplete": "",
                  "hidden": false,
                  "hideLabel": false,
                  "mask": false,
                  "autofocus": false,
                  "spellcheck": true,
                  "disabled": false,
                  "tableView": true,
                  "modalEdit": false,
                  "multiple": false,
                  "inputFormat": "plain",
                  "case": "",
                  "truncateMultipleSpaces": false,
                  "redrawOn": "",
                  "clearOnHide": true,
                  "customDefaultValue": "",
                  "calculateValue": "",
                  "allowCalculateOverride": false,
                  "validateOn": "change",
                  "validate": {
                    "required": false,
                    "pattern": "",
                    "customMessage": "",
                    "custom": "",
                    "customPrivate": false,
                    "json": "",
                    "minLength": "",
                    "maxLength": "",
                    "strictDateValidation": false,
                    "multiple": false,
                    "unique": false,
                  },
                  "unique": false,
                  "validateWhenHidden": false,
                  "errorLabel": "",
                  "errors": "",
                  "key": "email",
                  "tags": [],
                  "properties": {},
                  "conditional": {
                    "show": null,
                    "when": null,
                    "eq": "",
                    "json": "",
                  },
                  "customConditional": "",
                  "logic": [],
                  "attributes": {},
                  "type": "email",
                  "dataGridLabel": false,
                  "input": true,
                  "protected": false,
                  "persistent": true,
                  "refreshOn": "",
                  "dbIndex": false,
                  "calculateServer": false,
                  "overlay": {
                    "style": "",
                    "left": "",
                    "top": "",
                    "width": "",
                    "height": "",
                  },
                  "encrypted": false,
                  "showCharCount": false,
                  "showWordCount": false,
                  "allowMultipleMasks": false,
                  "addons": [],
                  "inputType": "email",
                  "inputMask": "",
                  "kickbox": {"enabled": false},
                  "id": "ef3dk59",
                  "defaultValue": null,
                },
              ],
              "size": "md",
              "width": 4,
              "currentWidth": 4,
            },
          ],
          "autoAdjust": false,
          "customClass": "",
          "hidden": false,
          "modalEdit": false,
          "key": "columns",
          "tags": [],
          "properties": {},
          "conditional": {"show": null, "when": null, "eq": "", "json": ""},
          "customConditional": "",
          "logic": [],
          "attributes": {},
          "type": "columns",
          "dataGridLabel": false,
          "input": false,
          "placeholder": "",
          "prefix": "",
          "suffix": "",
          "multiple": false,
          "defaultValue": null,
          "protected": false,
          "unique": false,
          "persistent": false,
          "clearOnHide": false,
          "refreshOn": "",
          "redrawOn": "",
          "tableView": false,
          "labelPosition": "top",
          "description": "",
          "errorLabel": "",
          "tooltip": "",
          "hideLabel": false,
          "tabindex": "",
          "disabled": false,
          "autofocus": false,
          "dbIndex": false,
          "customDefaultValue": "",
          "calculateValue": "",
          "calculateServer": false,
          "widget": null,
          "validateOn": "change",
          "validate": {
            "required": false,
            "custom": "",
            "customPrivate": false,
            "strictDateValidation": false,
            "multiple": false,
            "unique": false,
          },
          "overlay": {
            "style": "",
            "left": "",
            "top": "",
            "width": "",
            "height": "",
          },
          "allowCalculateOverride": false,
          "encrypted": false,
          "showCharCount": false,
          "showWordCount": false,
          "allowMultipleMasks": false,
          "addons": [],
          "tree": false,
          "lazyLoad": false,
          "id": "ebb8q97",
        },
        {
          "label": "Address",
          "labelPosition": "top",
          "enableManualMode": false,
          "disableClearIcon": false,
          "placeholder": "",
          "description": "",
          "tooltip": "",
          "customClass": "",
          "tabindex": "",
          "hidden": false,
          "hideLabel": false,
          "autofocus": false,
          "disabled": false,
          "tableView": false,
          "modalEdit": false,
          "multiple": false,
          "redrawOn": "",
          "clearOnHide": true,
          "customDefaultValue": "",
          "calculateValue": "",
          "allowCalculateOverride": false,
          "provider": "google",
          "manualModeViewString": "",
          "validateOn": "change",
          "validate": {
            "required": false,
            "customMessage": "",
            "custom": "",
            "customPrivate": false,
            "json": "",
            "strictDateValidation": false,
            "multiple": false,
            "unique": false,
          },
          "validateWhenHidden": false,
          "errorLabel": "",
          "errors": "",
          "key": "address",
          "tags": [],
          "properties": {},
          "conditional": {"show": null, "when": null, "eq": "", "json": ""},
          "customConditional": "",
          "logic": [],
          "attributes": {},
          "type": "address",
          "providerOptions": {
            "params": {
              "autocompleteOptions": {},
              "key": "HERE GOES API KEYYYY",
            },
          },
          "switchToManualModeLabel":
              "Can't find address? Switch to manual mode.",
          "dataGridLabel": false,
          "input": true,
          "prefix": "",
          "suffix": "",
          "protected": false,
          "unique": false,
          "persistent": true,
          "refreshOn": "",
          "dbIndex": false,
          "calculateServer": false,
          "widget": null,
          "overlay": {
            "style": "",
            "left": "",
            "top": "",
            "width": "",
            "height": "",
          },
          "encrypted": false,
          "showCharCount": false,
          "showWordCount": false,
          "allowMultipleMasks": false,
          "addons": [],
          "tree": true,
          "lazyLoad": false,
          "components": [
            {
              "label": "Address 1",
              "tableView": false,
              "key": "address1",
              "type": "textfield",
              "input": true,
              "customConditional":
                  "show = _.get(instance, 'parent.manualMode', false);",
              "id": "e7amgcq",
              "placeholder": "",
              "prefix": "",
              "customClass": "",
              "suffix": "",
              "multiple": false,
              "defaultValue": null,
              "protected": false,
              "unique": false,
              "persistent": true,
              "hidden": false,
              "clearOnHide": true,
              "refreshOn": "",
              "redrawOn": "",
              "modalEdit": false,
              "dataGridLabel": false,
              "labelPosition": "top",
              "description": "",
              "errorLabel": "",
              "tooltip": "",
              "hideLabel": false,
              "tabindex": "",
              "disabled": false,
              "autofocus": false,
              "dbIndex": false,
              "customDefaultValue": "",
              "calculateValue": "",
              "calculateServer": false,
              "widget": {"type": "input"},
              "attributes": {},
              "validateOn": "change",
              "validate": {
                "required": false,
                "custom": "",
                "customPrivate": false,
                "strictDateValidation": false,
                "multiple": false,
                "unique": false,
                "minLength": "",
                "maxLength": "",
                "pattern": "",
              },
              "conditional": {"show": null, "when": null, "eq": ""},
              "overlay": {
                "style": "",
                "left": "",
                "top": "",
                "width": "",
                "height": "",
              },
              "allowCalculateOverride": false,
              "encrypted": false,
              "showCharCount": false,
              "showWordCount": false,
              "properties": {},
              "allowMultipleMasks": false,
              "addons": [],
              "mask": false,
              "inputType": "text",
              "inputFormat": "plain",
              "inputMask": "",
              "displayMask": "",
              "spellcheck": true,
              "truncateMultipleSpaces": false,
            },
            {
              "label": "Address 2",
              "tableView": false,
              "key": "address2",
              "type": "textfield",
              "input": true,
              "customConditional":
                  "show = _.get(instance, 'parent.manualMode', false);",
              "id": "eyzu8j5",
              "placeholder": "",
              "prefix": "",
              "customClass": "",
              "suffix": "",
              "multiple": false,
              "defaultValue": null,
              "protected": false,
              "unique": false,
              "persistent": true,
              "hidden": false,
              "clearOnHide": true,
              "refreshOn": "",
              "redrawOn": "",
              "modalEdit": false,
              "dataGridLabel": false,
              "labelPosition": "top",
              "description": "",
              "errorLabel": "",
              "tooltip": "",
              "hideLabel": false,
              "tabindex": "",
              "disabled": false,
              "autofocus": false,
              "dbIndex": false,
              "customDefaultValue": "",
              "calculateValue": "",
              "calculateServer": false,
              "widget": {"type": "input"},
              "attributes": {},
              "validateOn": "change",
              "validate": {
                "required": false,
                "custom": "",
                "customPrivate": false,
                "strictDateValidation": false,
                "multiple": false,
                "unique": false,
                "minLength": "",
                "maxLength": "",
                "pattern": "",
              },
              "conditional": {"show": null, "when": null, "eq": ""},
              "overlay": {
                "style": "",
                "left": "",
                "top": "",
                "width": "",
                "height": "",
              },
              "allowCalculateOverride": false,
              "encrypted": false,
              "showCharCount": false,
              "showWordCount": false,
              "properties": {},
              "allowMultipleMasks": false,
              "addons": [],
              "mask": false,
              "inputType": "text",
              "inputFormat": "plain",
              "inputMask": "",
              "displayMask": "",
              "spellcheck": true,
              "truncateMultipleSpaces": false,
            },
            {
              "label": "City",
              "tableView": false,
              "key": "city",
              "type": "textfield",
              "input": true,
              "customConditional":
                  "show = _.get(instance, 'parent.manualMode', false);",
              "id": "exnpq5",
              "placeholder": "",
              "prefix": "",
              "customClass": "",
              "suffix": "",
              "multiple": false,
              "defaultValue": null,
              "protected": false,
              "unique": false,
              "persistent": true,
              "hidden": false,
              "clearOnHide": true,
              "refreshOn": "",
              "redrawOn": "",
              "modalEdit": false,
              "dataGridLabel": false,
              "labelPosition": "top",
              "description": "",
              "errorLabel": "",
              "tooltip": "",
              "hideLabel": false,
              "tabindex": "",
              "disabled": false,
              "autofocus": false,
              "dbIndex": false,
              "customDefaultValue": "",
              "calculateValue": "",
              "calculateServer": false,
              "widget": {"type": "input"},
              "attributes": {},
              "validateOn": "change",
              "validate": {
                "required": false,
                "custom": "",
                "customPrivate": false,
                "strictDateValidation": false,
                "multiple": false,
                "unique": false,
                "minLength": "",
                "maxLength": "",
                "pattern": "",
              },
              "conditional": {"show": null, "when": null, "eq": ""},
              "overlay": {
                "style": "",
                "left": "",
                "top": "",
                "width": "",
                "height": "",
              },
              "allowCalculateOverride": false,
              "encrypted": false,
              "showCharCount": false,
              "showWordCount": false,
              "properties": {},
              "allowMultipleMasks": false,
              "addons": [],
              "mask": false,
              "inputType": "text",
              "inputFormat": "plain",
              "inputMask": "",
              "displayMask": "",
              "spellcheck": true,
              "truncateMultipleSpaces": false,
            },
            {
              "label": "State",
              "tableView": false,
              "key": "state",
              "type": "textfield",
              "input": true,
              "customConditional":
                  "show = _.get(instance, 'parent.manualMode', false);",
              "id": "eaq8yp",
              "placeholder": "",
              "prefix": "",
              "customClass": "",
              "suffix": "",
              "multiple": false,
              "defaultValue": null,
              "protected": false,
              "unique": false,
              "persistent": true,
              "hidden": false,
              "clearOnHide": true,
              "refreshOn": "",
              "redrawOn": "",
              "modalEdit": false,
              "dataGridLabel": false,
              "labelPosition": "top",
              "description": "",
              "errorLabel": "",
              "tooltip": "",
              "hideLabel": false,
              "tabindex": "",
              "disabled": false,
              "autofocus": false,
              "dbIndex": false,
              "customDefaultValue": "",
              "calculateValue": "",
              "calculateServer": false,
              "widget": {"type": "input"},
              "attributes": {},
              "validateOn": "change",
              "validate": {
                "required": false,
                "custom": "",
                "customPrivate": false,
                "strictDateValidation": false,
                "multiple": false,
                "unique": false,
                "minLength": "",
                "maxLength": "",
                "pattern": "",
              },
              "conditional": {"show": null, "when": null, "eq": ""},
              "overlay": {
                "style": "",
                "left": "",
                "top": "",
                "width": "",
                "height": "",
              },
              "allowCalculateOverride": false,
              "encrypted": false,
              "showCharCount": false,
              "showWordCount": false,
              "properties": {},
              "allowMultipleMasks": false,
              "addons": [],
              "mask": false,
              "inputType": "text",
              "inputFormat": "plain",
              "inputMask": "",
              "displayMask": "",
              "spellcheck": true,
              "truncateMultipleSpaces": false,
            },
            {
              "label": "Country",
              "tableView": false,
              "key": "country",
              "type": "textfield",
              "input": true,
              "customConditional":
                  "show = _.get(instance, 'parent.manualMode', false);",
              "id": "e5z3fc",
              "placeholder": "",
              "prefix": "",
              "customClass": "",
              "suffix": "",
              "multiple": false,
              "defaultValue": null,
              "protected": false,
              "unique": false,
              "persistent": true,
              "hidden": false,
              "clearOnHide": true,
              "refreshOn": "",
              "redrawOn": "",
              "modalEdit": false,
              "dataGridLabel": false,
              "labelPosition": "top",
              "description": "",
              "errorLabel": "",
              "tooltip": "",
              "hideLabel": false,
              "tabindex": "",
              "disabled": false,
              "autofocus": false,
              "dbIndex": false,
              "customDefaultValue": "",
              "calculateValue": "",
              "calculateServer": false,
              "widget": {"type": "input"},
              "attributes": {},
              "validateOn": "change",
              "validate": {
                "required": false,
                "custom": "",
                "customPrivate": false,
                "strictDateValidation": false,
                "multiple": false,
                "unique": false,
                "minLength": "",
                "maxLength": "",
                "pattern": "",
              },
              "conditional": {"show": null, "when": null, "eq": ""},
              "overlay": {
                "style": "",
                "left": "",
                "top": "",
                "width": "",
                "height": "",
              },
              "allowCalculateOverride": false,
              "encrypted": false,
              "showCharCount": false,
              "showWordCount": false,
              "properties": {},
              "allowMultipleMasks": false,
              "addons": [],
              "mask": false,
              "inputType": "text",
              "inputFormat": "plain",
              "inputMask": "",
              "displayMask": "",
              "spellcheck": true,
              "truncateMultipleSpaces": false,
            },
            {
              "label": "Zip Code",
              "tableView": false,
              "key": "zip",
              "type": "textfield",
              "input": true,
              "customConditional":
                  "show = _.get(instance, 'parent.manualMode', false);",
              "id": "e649gor",
              "placeholder": "",
              "prefix": "",
              "customClass": "",
              "suffix": "",
              "multiple": false,
              "defaultValue": null,
              "protected": false,
              "unique": false,
              "persistent": true,
              "hidden": false,
              "clearOnHide": true,
              "refreshOn": "",
              "redrawOn": "",
              "modalEdit": false,
              "dataGridLabel": false,
              "labelPosition": "top",
              "description": "",
              "errorLabel": "",
              "tooltip": "",
              "hideLabel": false,
              "tabindex": "",
              "disabled": false,
              "autofocus": false,
              "dbIndex": false,
              "customDefaultValue": "",
              "calculateValue": "",
              "calculateServer": false,
              "widget": {"type": "input"},
              "attributes": {},
              "validateOn": "change",
              "validate": {
                "required": false,
                "custom": "",
                "customPrivate": false,
                "strictDateValidation": false,
                "multiple": false,
                "unique": false,
                "minLength": "",
                "maxLength": "",
                "pattern": "",
              },
              "conditional": {"show": null, "when": null, "eq": ""},
              "overlay": {
                "style": "",
                "left": "",
                "top": "",
                "width": "",
                "height": "",
              },
              "allowCalculateOverride": false,
              "encrypted": false,
              "showCharCount": false,
              "showWordCount": false,
              "properties": {},
              "allowMultipleMasks": false,
              "addons": [],
              "mask": false,
              "inputType": "text",
              "inputFormat": "plain",
              "inputMask": "",
              "displayMask": "",
              "spellcheck": true,
              "truncateMultipleSpaces": false,
            },
          ],
          "id": "ebk4j6f",
          "defaultValue": {},
        },
        {
          "legend": "Basic Computed Data",
          "tooltip": "",
          "customClass": "",
          "tabindex": "",
          "hidden": false,
          "disabled": false,
          "modalEdit": false,
          "key": "fieldSet",
          "tags": [],
          "properties": {},
          "conditional": {"show": null, "when": null, "eq": "", "json": ""},
          "customConditional": "",
          "logic": [],
          "attributes": {},
          "type": "fieldset",
          "label": "Field Set",
          "dataGridLabel": false,
          "input": false,
          "placeholder": "",
          "prefix": "",
          "suffix": "",
          "multiple": false,
          "defaultValue": null,
          "protected": false,
          "unique": false,
          "persistent": false,
          "clearOnHide": true,
          "refreshOn": "",
          "redrawOn": "",
          "tableView": false,
          "labelPosition": "top",
          "description": "",
          "errorLabel": "",
          "hideLabel": false,
          "autofocus": false,
          "dbIndex": false,
          "customDefaultValue": "",
          "calculateValue": "",
          "calculateServer": false,
          "widget": null,
          "validateOn": "change",
          "validate": {
            "required": false,
            "custom": "",
            "customPrivate": false,
            "strictDateValidation": false,
            "multiple": false,
            "unique": false,
          },
          "overlay": {
            "style": "",
            "left": "",
            "top": "",
            "width": "",
            "height": "",
          },
          "allowCalculateOverride": false,
          "encrypted": false,
          "showCharCount": false,
          "showWordCount": false,
          "allowMultipleMasks": false,
          "addons": [],
          "tree": false,
          "lazyLoad": false,
          "components": [
            {
              "label": "Text Field",
              "labelPosition": "top",
              "placeholder": "",
              "description": "",
              "tooltip": "",
              "prefix": "",
              "suffix": "",
              "widget": {"type": "input"},
              "inputMask": "",
              "displayMask": "",
              "applyMaskOn": "change",
              "allowMultipleMasks": false,
              "customClass": "",
              "tabindex": "",
              "autocomplete": "",
              "hidden": false,
              "hideLabel": false,
              "showWordCount": false,
              "showCharCount": false,
              "mask": false,
              "autofocus": false,
              "spellcheck": true,
              "disabled": false,
              "tableView": true,
              "modalEdit": false,
              "multiple": false,
              "inputFormat": "plain",
              "case": "",
              "truncateMultipleSpaces": false,
              "redrawOn": "",
              "clearOnHide": true,
              "customDefaultValue": "",
              "calculateValue": "",
              "allowCalculateOverride": false,
              "validateOn": "change",
              "validate": {
                "required": false,
                "pattern": "",
                "customMessage": "",
                "custom": "",
                "customPrivate": false,
                "json": "",
                "minLength": "",
                "maxLength": "",
                "strictDateValidation": false,
                "multiple": false,
                "unique": false,
              },
              "validateWhenHidden": false,
              "errorLabel": "",
              "errors": "",
              "key": "textField1",
              "tags": [],
              "properties": {},
              "conditional": {"show": null, "when": null, "eq": "", "json": ""},
              "customConditional": "",
              "logic": [],
              "attributes": {},
              "type": "textfield",
              "dataGridLabel": false,
              "input": true,
              "protected": false,
              "unique": false,
              "persistent": true,
              "refreshOn": "",
              "dbIndex": false,
              "calculateServer": false,
              "overlay": {
                "style": "",
                "left": "",
                "top": "",
                "width": "",
                "height": "",
              },
              "encrypted": false,
              "addons": [],
              "inputType": "text",
              "id": "e4aoe9",
              "defaultValue": null,
            },
          ],
          "id": "ef7n7it",
        },
        {
          "label": "Survey",
          "labelPosition": "top",
          "description": "",
          "tooltip": "",
          "customClass": "",
          "tabindex": "",
          "hidden": false,
          "hideLabel": false,
          "autofocus": false,
          "disabled": false,
          "tableView": false,
          "modalEdit": false,
          "questions": [
            {"label": "Are you happy?", "value": "areYouHappy", "tooltip": ""},
            {
              "label": "Are you single?",
              "value": "areYouSingle",
              "tooltip": "",
            },
            {
              "label": "want 1Millon usd?",
              "value": "want1MillonUsd",
              "tooltip": "",
            },
          ],
          "values": [
            {"label": "Yes", "value": "yes", "tooltip": ""},
            {"label": "No", "value": "no", "tooltip": ""},
            {"label": "Maybe", "value": "maybe", "tooltip": ""},
          ],
          "redrawOn": "",
          "clearOnHide": true,
          "customDefaultValue": "",
          "calculateValue": "",
          "allowCalculateOverride": false,
          "validate": {
            "required": false,
            "customMessage": "",
            "custom": "",
            "customPrivate": false,
            "json": "",
            "strictDateValidation": false,
            "multiple": false,
            "unique": false,
          },
          "validateWhenHidden": false,
          "errorLabel": "",
          "errors": "",
          "key": "survey",
          "tags": [],
          "properties": {},
          "conditional": {"show": null, "when": null, "eq": "", "json": ""},
          "customConditional": "",
          "logic": [],
          "attributes": {},
          "type": "survey",
          "dataGridLabel": false,
          "input": true,
          "placeholder": "",
          "prefix": "",
          "suffix": "",
          "multiple": false,
          "protected": false,
          "unique": false,
          "persistent": true,
          "refreshOn": "",
          "dbIndex": false,
          "calculateServer": false,
          "widget": null,
          "validateOn": "change",
          "overlay": {
            "style": "",
            "left": "",
            "top": "",
            "width": "",
            "height": "",
          },
          "encrypted": false,
          "showCharCount": false,
          "showWordCount": false,
          "allowMultipleMasks": false,
          "addons": [],
          "id": "exts3ve",
          "defaultValue": {},
        },
        {
          "label": "Signature",
          "footer": "Sign above",
          "labelPosition": "top",
          "width": "100%",
          "height": "150px",
          "backgroundColor": "rgb(245,245,235)",
          "penColor": "black",
          "description": "",
          "tooltip": "",
          "customClass": "",
          "tabindex": "",
          "hidden": false,
          "hideLabel": false,
          "disabled": false,
          "tableView": false,
          "modalEdit": false,
          "redrawOn": "",
          "clearOnHide": true,
          "customDefaultValue": "",
          "calculateValue": "",
          "allowCalculateOverride": false,
          "validate": {
            "required": true,
            "customMessage": "",
            "custom": "",
            "customPrivate": false,
            "json": "",
            "strictDateValidation": false,
            "multiple": false,
            "unique": false,
          },
          "validateWhenHidden": false,
          "errorLabel": "",
          "errors": "",
          "key": "signature",
          "tags": [],
          "properties": {},
          "conditional": {"show": null, "when": null, "eq": "", "json": ""},
          "customConditional": "",
          "logic": [],
          "attributes": {},
          "type": "signature",
          "keepOverlayRatio": true,
          "dataGridLabel": false,
          "input": true,
          "placeholder": "",
          "prefix": "",
          "suffix": "",
          "multiple": false,
          "defaultValue": null,
          "protected": false,
          "unique": false,
          "persistent": true,
          "refreshOn": "",
          "autofocus": false,
          "dbIndex": false,
          "calculateServer": false,
          "widget": {"type": "input"},
          "validateOn": "change",
          "overlay": {
            "style": "",
            "left": "",
            "top": "",
            "width": "",
            "height": "",
          },
          "encrypted": false,
          "showCharCount": false,
          "showWordCount": false,
          "allowMultipleMasks": false,
          "addons": [],
          "minWidth": "0.5",
          "maxWidth": "2.5",
          "id": "eap5a2s",
        },
      ],
      "id": "evar3m",
      "input": false,
      "placeholder": "",
      "prefix": "",
      "customClass": "",
      "suffix": "",
      "multiple": false,
      "defaultValue": null,
      "protected": false,
      "unique": false,
      "persistent": false,
      "hidden": false,
      "clearOnHide": false,
      "refreshOn": "",
      "redrawOn": "",
      "tableView": false,
      "modalEdit": false,
      "dataGridLabel": false,
      "labelPosition": "top",
      "description": "",
      "errorLabel": "",
      "tooltip": "",
      "hideLabel": false,
      "tabindex": "",
      "disabled": false,
      "autofocus": false,
      "dbIndex": false,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "widget": null,
      "attributes": {},
      "validateOn": "change",
      "validate": {
        "required": false,
        "custom": "",
        "customPrivate": false,
        "strictDateValidation": false,
        "multiple": false,
        "unique": false,
      },
      "conditional": {"show": null, "when": null, "eq": ""},
      "overlay": {
        "style": "",
        "left": "",
        "top": "",
        "width": "",
        "height": "",
      },
      "allowCalculateOverride": false,
      "encrypted": false,
      "showCharCount": false,
      "showWordCount": false,
      "properties": {},
      "allowMultipleMasks": false,
      "addons": [],
      "tree": false,
      "lazyLoad": false,
      "theme": "default",
      "breadcrumb": "default",
    },
  ],
};
